@startuml
title Relation Schema
hide circle

entity Користувачка {
  (PK)id_korystuvachka
  --
  Прізвище
  Ім'я
  Вік
  Інвалідність
  Номер_телефону
 (FK)id_dodatok
}



entity Інформація {
  (PK)id_informacion
  --
  Дата_започаткування
  Країна
  Інтенсивність
  Інвалідність
  Тип_танцю
  Історія
 (FK) id_dance
}

entity Відео {
  (PK)id_video
  --
  Назва
  Розмір
  Тривалість
  Формат
  (FK) id_dance 
}

entity Танець {
  (PK)id_dance
  --
 Назва
  Додаткова_інформація
  (FK)id_dodatok
}

entity Застосунок_для_танців {
  (PK)id_dodatok
  --
  Назва
  Тип
  Розмір
  Мінімальні_характеристики
  Зміст
}

entity КористувачкаІнформація {
  (PK)id_informacion
  (PK)id_korystuvachka
}

 entity КористувачкаВідео {
  (PK)id_video
  (PK)id_korystuvachka
}

Користувачка --{ КористувачкаВідео
Відео --{ КористувачкаВідео

Користувачка --{ КористувачкаІнформація
Інформація --{ КористувачкаІнформація

Застосунок_для_танців --{ Танець

Застосунок_для_танців --{ Користувачка

Танець -- Інформація

Танець --{ Відео
@enduml
