@startuml
title Classes Diagram

Class Застосунок_для_танців
Class Користувачка
Class Танець
Class Інформація
Class Відео

Застосунок_для_танців"1" -up-> "*"Користувачка : надає
Користувачка"*" -up-> "*"Відео : отримує
Користувачка"*" -up-> "*"Інформація: отримує
Танець"*" --o Застосунок_для_танців : contains
Інформація"1" --o "1"Танець : contains
Відео"*" --o "*"Танець : contains

@enduml
