@startuml

title Conditional - Activity Diagram 

start

:Користувачка вибирає певну категорію танців за інтенсивністю;
: Застосунок видає віконце;

if (Саме ця категорія?) then (Так)
  :Система видає танці з цієї категорії ;
else (Ні)
  :Система повертає до обирання категорії;
endif

stop

@enduml
