@startuml
title Usecase for Information system
left to right direction

actor Користувачка
actor Кухар
actor Сервіс_pay
actor Курєр
rectangle Software {
  
  Користувачка -- (перегляд переліку страв)
  
  Користувачка -- (формування замовлення)

  Кухар -- (отримання онлайн-замовлення)
  Кухар -- (готування страв)
  Кухар -- (формування споживчого пакету)
Кухар -- (передання Курєру)
  Сервіс_pay -- (Сервіс_pay)
  Користувачка -- (отримання замовлення)
  
  (перегляд переліку страв) ..> (Авторизація) : <<include>>

  (формування замовлення) ..> (Авторизація) : <<include>>
  (Сервіс_pay)..> (СплаченняПослуги) : <<extend>>
  (СплаченняПослуги)..> (Авторизація) : <<include>>
 Курєр.> (отримання замовлення) : <<include>>
  Курєр.> (передання Курєру) : <<include>>
  
}

@enduml
